// these are the color themes and reaction diffusion themes
const presets = {
  Ocean: {
    feed: 0.0174,
    kill: 0.043,
    dt: 0.5,
    iterations: 5,
    scale: 1,
    radius: 0.05,
    wrap: false,
    refraction: 0.74,
    zoom: 1,
    render: {
      palette: {
        brightness: { x: 0, y: 0.6, z: 1 },
        contrast: { x: 1, y: 1, z: 1 },
        frequency: { x: 3, y: 3, z: 3 },
        phase: { x: 0, y: 0, z: 0 },
      },
      emboss: false,
      offset: 0.1,
      pixel_size: 4.0,
      pixel_radius: 0.9,
      pixelate: 0,
      screen_grain: false,
      screen_tint: "#ffffffb0", // "#c64962ff",
    },
    drumbit: {
      sound_kit: "water",
      circular_pads: true,
    },
  },
  Maze: {
    feed: 0.03239,
    kill: 0.05799,
    dt: 1.5,
    iterations: 5,
    scale: 1.5,
    radius: 0.02,
    wrap: false,
    refraction: 1.0,
    zoom: 1.0,
    render: {
      palette: {
        brightness: { x: 0, y: 0, z: 0 },
        contrast: { x: 1, y: 1, z: 1 },
        frequency: { x: 1, y: 1, z: 1 },
        phase: { x: 0.6, y: 0.79, z: 0.82 },
      },
      emboss: false,
      offset: 0,
      pixel_size: 4.0,
      pixel_radius: 0.9,
      pixelate: 0,
      screen_grain: true,
      screen_tint: "#ffffffb0", // "#c64962ff",
    },
    drumbit: {
      sound_kit: "fusion_drum",
      circular_pads: true,
    },
  },
  Toxicant: {
    feed: 0.00761,
    kill: 0.03473,
    dt: 1.5,
    iterations: 5,
    scale: 1.5,
    radius: 0.01,
    wrap: false,
    refraction: 1.7,
    zoom: 1.0,
    render: {
      palette: {
        brightness: { x: 0, y: 0, z: 0 },
        contrast: { x: 0, y: 1, z: 1 },
        frequency: { x: 5, y: 5, z: 5 },
        phase: { x: 0.92, y: 0.72, z: 0.7 },
      },
      emboss: true,
      offset: 0,
      pixel_size: 4.0,
      pixel_radius: 0.9,
      pixelate: 0,
      screen_grain: false,
      screen_tint: "#ffffffb0", // "#c64962ff",
    },
    drumbit: {
      sound_kit: "tabla_drone",
      circular_pads: true,
    },
  },
};

/*
 * Original presets

// these are the color themes and reaction diffusion themes
const presets = {
  Petroleum: {
    feed: 0.02011,
    kill: 0.04994,
    dt: 1.5,
    iterations: 5,
    scale: 2,
    radius: 0.02,
    wrap: false,
    refraction: 1.0,
    zoom: 4.0,
    render: {
      palette: {
        brightness: { x: 0.5, y: 0.5, z: 0.5 },
        contrast: { x: 0.5, y: 0.5, z: 0.5 },
        frequency: { x: 1, y: 1, z: 1 },
        phase: { x: 0.1, y: 0.1, z: 0.1 },
      },
      emboss: true,
      offset: 0.5,
      pixel_size: 4.0,
      pixel_radius: 0.9,
      pixelate: true,
    },
  },
  Reaction: {
    feed: 0.02109,
    kill: 0.05666,
    dt: 1.5,
    iterations: 5,
    scale: 1,
    radius: 0.001,
    wrap: false,
    refraction: 1.0,
    zoom: 4.0,
    render: {
      palette: {
        brightness: { x: 0, y: 0.59, z: 0.76 },
        contrast: { x: 1, y: 1, z: 1 },
        frequency: { x: 1, y: 1, z: 1 },
        phase: { x: 0, y: 0, z: 1 },
      },
      emboss: false,
      offset: 0.5,
      pixel_size: 4.0,
      pixel_radius: 0.9,
      pixelate: true,
    },
  },
  Unreal: {
    feed: 0.01565,
    kill: 0.04552,
    dt: 1.5,
    iterations: 5,
    scale: 1,
    radius: 0.001,
    wrap: false,
    refraction: 1.0,
    zoom: 4.0,
    render: {
      palette: {
        brightness: { x: 1, y: 0, z: 0.9 },
        contrast: { x: 1, y: 1, z: 1 },
        frequency: { x: 2, y: 3, z: 3 },
        phase: { x: 0.92, y: 0.72, z: 0.7 },
      },
      emboss: false,
      offset: 0.5,
      pixel_size: 4.0,
      pixel_radius: 0.9,
      pixelate: true,
    },
  },
  Metal: {
    feed: 0.03413,
    kill: 0.05944,
    dt: 1.5,
    iterations: 5,
    scale: 1,
    radius: 0.02,
    wrap: false,
    refraction: 1.0,
    zoom: 4.0,
    render: {
      palette: {
        brightness: { x: 0.83, y: 1, z: 1 },
        contrast: { x: 1, y: 1, z: 1 },
        frequency: { x: 1, y: 1, z: 1 },
        phase: { x: 0, y: 0, z: 1 },
      },
      emboss: true,
      offset: 0.5,
      pixel_size: 4.0,
      pixel_radius: 0.9,
      pixelate: true,
    },
  },
  Ocean: {
    feed: 0.0174,
    kill: 0.043,
    dt: 0.5,
    iterations: 5,
    scale: 1,
    radius: 0.05,
    wrap: false,
    refraction: 0.74,
    zoom: 3.87,
    render: {
      palette: {
        brightness: { x: 0, y: 0.6, z: 1 },
        contrast: { x: 1, y: 1, z: 1 },
        frequency: { x: 3, y: 3, z: 3 },
        phase: { x: 0, y: 0, z: 0 },
      },
      emboss: false,
      offset: 0.1,
      pixel_size: 4.0,
      pixel_radius: 0.9,
      pixelate: true,
    },
  },
  Swirl: {
    feed: 0.00761,
    kill: 0.03473,
    dt: 1.5,
    iterations: 5,
    scale: 1.5,
    radius: 0.01,
    wrap: false,
    refraction: 1.0,
    zoom: 4.0,
    render: {
      palette: {
        brightness: { x: 0.75, y: 0.85, z: 0.75 },
        contrast: { x: 1, y: 1, z: 1 },
        frequency: { x: 2, y: 2, z: 2 },
        phase: { x: 0.3, y: 0.2, z: 0.1 },
      },
      emboss: false,
      offset: 0.45,
      pixel_size: 4.0,
      pixel_radius: 0.9,
      pixelate: true,
    },
  },
  Maze: {
    feed: 0.03239,
    kill: 0.05799,
    dt: 1.5,
    iterations: 5,
    scale: 1.5,
    radius: 0.02,
    wrap: false,
    refraction: 1.0,
    zoom: 4.0,
    render: {
      palette: {
        brightness: { x: 0, y: 0, z: 0 },
        contrast: { x: 1, y: 1, z: 1 },
        frequency: { x: 1, y: 1, z: 1 },
        phase: { x: 0.6, y: 0.79, z: 0.82 },
      },
      emboss: false,
      offset: 0,
      pixel_size: 4.0,
      pixel_radius: 0.9,
      pixelate: true,
    },
  },
  Heritage: {
    feed: 0.06522,
    kill: 0.06311,
    dt: 2,
    iterations: 5,
    scale: 1,
    radius: 0.001,
    wrap: false,
    refraction: 1.0,
    zoom: 4.0,
    render: {
      palette: {
        brightness: { x: 1, y: 0.15, z: 0.3 },
        contrast: { x: 1, y: 1, z: 0.5 },
        frequency: { x: 1, y: 0.5, z: 0.5 },
        phase: { x: 0.1, y: 0.1, z: 0.2 },
      },
      emboss: true,
      offset: 0.32,
      pixel_size: 4.0,
      pixel_radius: 0.9,
      pixelate: true,
    },
  },
  Toxicant: {
    feed: 0.00761,
    kill: 0.03473,
    dt: 1.5,
    iterations: 5,
    scale: 1.5,
    radius: 0.01,
    wrap: false,
    refraction: 1.0,
    zoom: 4.0,
    render: {
      palette: {
        brightness: { x: 0, y: 0, z: 0 },
        contrast: { x: 0, y: 1, z: 1 },
        frequency: { x: 5, y: 5, z: 5 },
        phase: { x: 0.92, y: 0.72, z: 0.7 },
      },
      emboss: true,
      offset: 0,
      pixel_size: 4.0,
      pixel_radius: 0.9,
      pixelate: true,
    },
  },
  Membrane: {
    feed: 0.02717,
    kill: 0.05254,
    dt: 2,
    iterations: 5,
    scale: 1,
    radius: 0.001,
    wrap: false,
    refraction: 1.0,
    zoom: 4.0,
    render: {
      palette: {
        brightness: { x: 0.35, y: 0.45, z: 0.5 },
        contrast: { x: 0.6, y: 0.6, z: 0.6 },
        frequency: { x: 1.5, y: 1.3, z: 1.3 },
        phase: { x: 0, y: 0, z: 0 },
      },
      emboss: true,
      offset: 0.1,
      pixel_size: 4.0,
      pixel_radius: 0.9,
      pixelate: true,
    },
  },
  Flux: {
    feed: 0.02609,
    kill: 0.05699,
    dt: 1.5,
    iterations: 4,
    scale: 2,
    radius: 0.02,
    wrap: false,
    refraction: 1.0,
    zoom: 4.0,
    render: {
      palette: {
        brightness: { x: 0.2, y: 0.5, z: 0.5 },
        contrast: { x: 1, y: 0.59, z: 0.5 },
        frequency: { x: 1, y: 1, z: 1 },
        phase: { x: 0.1, y: 0.07, z: 0 },
      },
      emboss: false,
      offset: -0.33,
      pixel_size: 4.0,
      pixel_radius: 0.9,
      pixelate: true,
    },
  },
  Lines: {
    feed: 0.04348,
    kill: 0.06311,
    dt: 2,
    iterations: 5,
    scale: 1,
    radius: 0.001,
    wrap: false,
    refraction: 1.0,
    zoom: 4.0,
    render: {
      palette: {
        brightness: { x: 0.5, y: 0.5, z: 0.5 },
        contrast: { x: 0.5, y: 0.5, z: 0.5 },
        frequency: { x: 1, y: 1, z: 1 },
        phase: { x: 0, y: 0, z: 0 },
      },
      emboss: false,
      offset: 0.15,
      pixel_size: 4.0,
      pixel_radius: 0.9,
      pixelate: true,
    },
  },
};

*/
