// these are the color themes and reaction diffusion themes
const presets = {
  Ocean: {
    feed: 0.0174,
    kill: 0.043,
    dt: 0.5,
    iterations: 5,
    scale: 1,
    radius: 0.05,
    wrap: false,
    refraction: 0.74,
    zoom: 1,
    render: {
      palette: {
        brightness: { x: 0, y: 0.6, z: 1 },
        contrast: { x: 1, y: 1, z: 1 },
        frequency: { x: 3, y: 3, z: 3 },
        phase: { x: 0, y: 0, z: 0 },
      },
      emboss: false,
      offset: 0.1,
      pixel_size: 4.0,
      pixel_radius: 0.9,
      pixelate: false,
      screen_grain: false,
      screen_tint: "#ffffffb0", // "#c64962ff",
    },
    drumbit: {
      sound_kit: "water",
      circular_pads: true,
    },
  },
  Maze: {
    feed: 0.03239,
    kill: 0.05799,
    dt: 1.5,
    iterations: 5,
    scale: 1.5,
    radius: 0.02,
    wrap: false,
    refraction: 1.0,
    zoom: 1.0,
    render: {
      palette: {
        brightness: { x: 0, y: 0, z: 0 },
        contrast: { x: 1, y: 1, z: 1 },
        frequency: { x: 1, y: 1, z: 1 },
        phase: { x: 0.6, y: 0.79, z: 0.82 },
      },
      emboss: false,
      offset: 0,
      pixel_size: 4.0,
      pixel_radius: 0.9,
      pixelate: false,
      screen_grain: true,
      screen_tint: "#ffffffb0", // "#c64962ff",
    },
    drumbit: {
      sound_kit: "fusion_drum",
      circular_pads: true,
    },
  },
  Toxicant: {
    feed: 0.00761,
    kill: 0.03473,
    dt: 1.5,
    iterations: 5,
    scale: 1.5,
    radius: 0.01,
    wrap: false,
    refraction: 1.7,
    zoom: 1.0,
    render: {
      palette: {
        brightness: { x: 0, y: 0, z: 0 },
        contrast: { x: 0, y: 1, z: 1 },
        frequency: { x: 5, y: 5, z: 5 },
        phase: { x: 0.92, y: 0.72, z: 0.7 },
      },
      emboss: true,
      offset: 0,
      pixel_size: 4.0,
      pixel_radius: 0.9,
      pixelate: false,
      screen_grain: false,
      screen_tint: "#ffffffb0", // "#c64962ff",
    },
    drumbit: {
      sound_kit: "tabla_drone",
      circular_pads: true,
    },
  },
};
